name = "MDLovoFit"
uuid = "55da9f78-c647-4a46-be5d-0de490449a34"
authors = ["Leandro Martinez <lmartine@unicamp.br> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
